# Generated by Django 4.2.25 on 2025-10-04 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLayerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('active_layers', models.JSONField(default=list)),
                ('layer_opacity', models.JSONField(default=dict)),
                ('center_lat', models.FloatField(default=0.0)),
                ('center_lon', models.FloatField(default=0.0)),
                ('zoom_level', models.IntegerField(default=2)),
                ('projection', models.CharField(default='EPSG:4326', max_length=50)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldviewImageOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('published_date', models.DateField()),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('layers_used', models.JSONField(blank=True, default=list)),
                ('satellite', models.CharField(blank=True, max_length=255)),
                ('instrument', models.CharField(blank=True, max_length=255)),
                ('permalink', models.URLField(blank=True, max_length=1000)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worldview Image of the Week',
                'verbose_name_plural': 'Worldview Images of the Week',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='gibs_worldv_publish_15b7a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='GIBSLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('format_type', models.CharField(max_length=50)),
                ('projection', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('temporal_resolution', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('wraparound', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['layer_id'], name='gibs_gibsla_layer_i_0037be_idx'), models.Index(fields=['category'], name='gibs_gibsla_categor_25f763_idx')],
            },
        ),
    ]
