# Generated by Django 4.2.25 on 2025-10-04 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APODImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('hdurl', models.URLField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(default='image', max_length=20)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'APOD Image',
                'verbose_name_plural': 'APOD Images',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CelestialCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('crater', 'Crater'), ('mountain', 'Mountain'), ('galaxy', 'Galaxy'), ('nebula', 'Nebula'), ('star', 'Star'), ('planet', 'Planet'), ('other', 'Other')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('body', models.CharField(choices=[('Moon', 'Moon'), ('Mars', 'Mars'), ('Space', 'Space'), ('Earth', 'Earth'), ('Jupiter', 'Jupiter'), ('Saturn', 'Saturn'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apod_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates', to='apod.apodimage')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'body')},
            },
        ),
    ]
